### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by yxliang01** [duaraghav8/soltar#12]
Hi @duaraghav8 , when I was looking up for AST to Solidity tools/libraries, soltar happens to be the first and the only result. As what it looks like, it doesn't support many new features of newer version of Solidity. Do you plan to add the support?

Thanks! :)

**Comment by duaraghav8** [comment]
No. This repo is no longer being maintained. If you'd like to work on it, best things is to maintain your own fork.
